name: Covalent CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run format:check
      - run: npx nx affected --target=scsslint --base=remotes/origin/${{ github.event.pull_request.base.sha }} --head=remotes/origin/${{ github.sha }}
      - run: npx nx affected --target=lint --base=remotes/origin/${{ github.event.pull_request.base.sha }} --head=remotes/origin/${{ github.sha }}

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx nx affected --target=test --base=remotes/origin/${{ github.event.pull_request.base.sha }} --head=remotes/origin/${{ github.sha }}

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx nx affected --target=e2e --base=remotes/origin/${{ github.event.pull_request.base.sha }} --head=remotes/origin/${{ github.sha }}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx nx affected --target=build --base=remotes/origin/${{ github.event.pull_request.base.sha }} --head=remotes/origin/${{ github.sha }}
